#!/bin/bash
set -e

realpath() (
    TARGET=$1
    cd $(dirname "$TARGET")
    TARGET=$(basename "$TARGET")
    while [ -L "$TARGET" ] ; do
        TARGET=$(readlink "$TARGET")
        cd $(dirname "$TARGET")
        TARGET=$(basename "$TARGET")
    done
    DIR=$(pwd -P)
    echo "$DIR/$TARGET"
)
BIN=$(dirname $(realpath "${BASH_SOURCE%/*}/${0##*/}"))

PYTHON_SYS_EXECUTABLE="$BIN/../../.venv/bin/python" exec $(basename "$0") "$@"
